### ISSUE TITLE
pull updated dcp for windows compatibility

### ISSUE THREAD

**Issue by Floyddotnet** [suguru03/mocha-parallel-executor#1]
In windows, enviorement variables could have special charaters like "ProgramFiles(x86)". deepcopy, called from line (https://github.com/suguru03/mocha-parallel-executor/blob/master/lib/executor.js#L69), throws an exception until pull this fix (https://github.com/suguru03/dcp/pull/2) into dpc and update mocha-parallel-executor to the new version.

**Comment by suguru03** [comment]
Thanks for the issue! 
I fixed and published it on `v0.3.1`. 😄

**Comment by Floyddotnet** [comment]
it works, thanks :+1:
